/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scene.glb --transform 
Files: public/scene.glb [3.11KB] > /Users/everton/Documents/dev/modular_kitchen/scene-transformed.glb [1.21KB] (61%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mod_base_.geometry} material={nodes.mod_base_.material} position={[0, 1, 0]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
