/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scene.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    base: THREE.Mesh
    base_1: THREE.Mesh
    fridge: THREE.Mesh
    fridge_1: THREE.Mesh
    fridge_2: THREE.Mesh
    fridge_3: THREE.Mesh
    fridge_4: THREE.Mesh
    fridge_5: THREE.Mesh
    fridge_6: THREE.Mesh
    grill: THREE.Mesh
    grill_1: THREE.Mesh
    grill_2: THREE.Mesh
    grill_3: THREE.Mesh
    grill_4: THREE.Mesh
    grill_5: THREE.Mesh
    grill_6: THREE.Mesh
    grill_7: THREE.Mesh
    grill_8: THREE.Mesh
    grill_9: THREE.Mesh
    sink_on: THREE.Mesh
    sink_on_1: THREE.Mesh
    sink_on_2: THREE.Mesh
    sink_on_3: THREE.Mesh
    drawer: THREE.Mesh
    drawer_1: THREE.Mesh
    mod_sink_off: THREE.Mesh
  }
  materials: {
    ['Outdoor_Kitchen_02_Material #133']: THREE.MeshStandardMaterial
    mat_handle: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #68']: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #70']: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #115']: THREE.MeshPhysicalMaterial
    ['Outdoor_Kitchen_02_Material #69']: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #128']: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #134']: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #40']: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #41']: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #43']: THREE.MeshPhysicalMaterial
    ['Outdoor_Kitchen_02_Material #42']: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #58']: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #67']: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #66']: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #64']: THREE.MeshStandardMaterial
    sink: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #137']: THREE.MeshStandardMaterial
    ['Outdoor_Kitchen_02_Material #136']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.589, 0, -0.001]}>
        <mesh geometry={nodes.fridge.geometry} material={materials['Outdoor_Kitchen_02_Material #133']} />
        <mesh geometry={nodes.fridge_1.geometry} material={materials['Outdoor_Kitchen_02_Material #68']} />
        <mesh geometry={nodes.fridge_2.geometry} material={materials['Outdoor_Kitchen_02_Material #70']} />
        <mesh geometry={nodes.fridge_3.geometry} material={materials['Outdoor_Kitchen_02_Material #115']} />
        <mesh geometry={nodes.fridge_4.geometry} material={materials['Outdoor_Kitchen_02_Material #69']} />
        <mesh geometry={nodes.fridge_5.geometry} material={materials['Outdoor_Kitchen_02_Material #128']} />
        <mesh geometry={nodes.fridge_6.geometry} material={materials['Outdoor_Kitchen_02_Material #134']} />
      </group>
      <group position={[-0.762, 0, 0]}>
        <mesh geometry={nodes.grill.geometry} material={materials['Outdoor_Kitchen_02_Material #40']} />
        <mesh geometry={nodes.grill_1.geometry} material={materials['Outdoor_Kitchen_02_Material #41']} />
        <mesh geometry={nodes.grill_2.geometry} material={materials['Outdoor_Kitchen_02_Material #43']} />
        <mesh geometry={nodes.grill_3.geometry} material={materials['Outdoor_Kitchen_02_Material #42']} />
        <mesh geometry={nodes.grill_4.geometry} material={materials['Outdoor_Kitchen_02_Material #58']} />
        <mesh geometry={nodes.grill_5.geometry} material={materials['Outdoor_Kitchen_02_Material #133']} />
        <mesh geometry={nodes.grill_6.geometry} material={materials['Outdoor_Kitchen_02_Material #67']} />
        <mesh geometry={nodes.grill_7.geometry} material={materials['Outdoor_Kitchen_02_Material #66']} />
        <mesh geometry={nodes.grill_8.geometry} material={materials['Outdoor_Kitchen_02_Material #64']} />
        <mesh geometry={nodes.grill_9.geometry} material={materials['Outdoor_Kitchen_02_Material #134']} />
      </group>
      <group position={[-0.025, 0.727, 0.126]}>
        <mesh geometry={nodes.sink_on.geometry} material={materials.sink} />
        <mesh geometry={nodes.sink_on_1.geometry} material={materials['Outdoor_Kitchen_02_Material #134']} />
        <mesh geometry={nodes.sink_on_2.geometry} material={materials['Outdoor_Kitchen_02_Material #137']} />
        <mesh geometry={nodes.sink_on_3.geometry} material={materials['Outdoor_Kitchen_02_Material #136']} />
      </group>
      <mesh geometry={nodes.mod_sink_off.geometry} material={materials['Outdoor_Kitchen_02_Material #134']} />
      <mesh geometry={nodes.base.geometry} material={materials['Outdoor_Kitchen_02_Material #133']} />
      <mesh geometry={nodes.base_1.geometry} material={materials.mat_handle} />
      <mesh geometry={nodes.drawer.geometry} material={materials['Outdoor_Kitchen_02_Material #133']} />
      <mesh geometry={nodes.drawer_1.geometry} material={materials.mat_handle} />
    </group>
  )
}

useGLTF.preload('/scene.glb')
