/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scene.glb --output src/modules/scene/components/KitchenScene.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { instance } from 'three/tsl'

type GLTFResult = GLTF & {
  nodes: {
    mod_base: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    mod_drawer: THREE.Mesh
  }
  materials: {}
  // animations: GLTFAction[]
}

type instance = {
  module: string;
};

const instances : instance[] = [{module: 'mod_base'}];

export function KitchenScene(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/scene.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      {instances.map((instance) => {
        const nodeName = instance.module as keyof typeof nodes;
        const node = nodes[nodeName];
        
        return (
          <>
          /** IF istance hasSink in tru Render another mesh on TOP 'mod_sink'
           */
          <mesh 
            key={instance.module}
            geometry={node?.geometry} 
            material={node?.material} 
            position={[0, 0.002, -0.287]}
          >
            <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[-0.217, 0.311, 0.275]} />
            <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[0.217, 0.3, 0.275]} />
          </mesh>
          </>
        );
      })}
    </group>
  )
}

useGLTF.preload('/scene.glb')
