/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scene.glb -o src/modules/scene/components/Model.tsx -t -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mod_base_: THREE.Mesh
    mod_drawer: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mod_base_.geometry} material={nodes.mod_base_.material} position={[0, 1, 0]} />
      <mesh geometry={nodes.mod_drawer.geometry} material={nodes.mod_drawer.material} position={[0, 1, 0]} />
    </group>
  )
}

useGLTF.preload('/scene.glb')
